// Automatically generated Grand Piano 88-key mapping constants. Do not edit manually.
export const pianoSamples: Record<number, any> = {
  21: require('../../assets/audio/A0.mp3'), // A0
  22: require('../../assets/audio/Bb0.mp3'), // Bb0
  23: require('../../assets/audio/B0.mp3'), // B0
  24: require('../../assets/audio/C1.mp3'), // C1
  25: require('../../assets/audio/Db1.mp3'), // Db1
  26: require('../../assets/audio/D1.mp3'), // D1
  27: require('../../assets/audio/Eb1.mp3'), // Eb1
  28: require('../../assets/audio/E1.mp3'), // E1
  29: require('../../assets/audio/F1.mp3'), // F1
  30: require('../../assets/audio/Gb1.mp3'), // Gb1
  31: require('../../assets/audio/G1.mp3'), // G1
  32: require('../../assets/audio/Ab1.mp3'), // Ab1
  33: require('../../assets/audio/A1.mp3'), // A1
  34: require('../../assets/audio/Bb1.mp3'), // Bb1
  35: require('../../assets/audio/B1.mp3'), // B1
  36: require('../../assets/audio/C2.mp3'), // C2
  37: require('../../assets/audio/Db2.mp3'), // Db2
  38: require('../../assets/audio/D2.mp3'), // D2
  39: require('../../assets/audio/Eb2.mp3'), // Eb2
  40: require('../../assets/audio/E2.mp3'), // E2
  41: require('../../assets/audio/F2.mp3'), // F2
  42: require('../../assets/audio/Gb2.mp3'), // Gb2
  43: require('../../assets/audio/G2.mp3'), // G2
  44: require('../../assets/audio/Ab2.mp3'), // Ab2
  45: require('../../assets/audio/A2.mp3'), // A2
  46: require('../../assets/audio/Bb2.mp3'), // Bb2
  47: require('../../assets/audio/B2.mp3'), // B2
  48: require('../../assets/audio/C3.mp3'), // C3
  49: require('../../assets/audio/Db3.mp3'), // Db3
  50: require('../../assets/audio/D3.mp3'), // D3
  51: require('../../assets/audio/Eb3.mp3'), // Eb3
  52: require('../../assets/audio/E3.mp3'), // E3
  53: require('../../assets/audio/F3.mp3'), // F3
  54: require('../../assets/audio/Gb3.mp3'), // Gb3
  55: require('../../assets/audio/G3.mp3'), // G3
  56: require('../../assets/audio/Ab3.mp3'), // Ab3
  57: require('../../assets/audio/A3.mp3'), // A3
  58: require('../../assets/audio/Bb3.mp3'), // Bb3
  59: require('../../assets/audio/B3.mp3'), // B3
  60: require('../../assets/audio/C4.mp3'), // C4
  61: require('../../assets/audio/Db4.mp3'), // Db4
  62: require('../../assets/audio/D4.mp3'), // D4
  63: require('../../assets/audio/Eb4.mp3'), // Eb4
  64: require('../../assets/audio/E4.mp3'), // E4
  65: require('../../assets/audio/F4.mp3'), // F4
  66: require('../../assets/audio/Gb4.mp3'), // Gb4
  67: require('../../assets/audio/G4.mp3'), // G4
  68: require('../../assets/audio/Ab4.mp3'), // Ab4
  69: require('../../assets/audio/A4.mp3'), // A4
  70: require('../../assets/audio/Bb4.mp3'), // Bb4
  71: require('../../assets/audio/B4.mp3'), // B4
  72: require('../../assets/audio/C5.mp3'), // C5
  73: require('../../assets/audio/Db5.mp3'), // Db5
  74: require('../../assets/audio/D5.mp3'), // D5
  75: require('../../assets/audio/Eb5.mp3'), // Eb5
  76: require('../../assets/audio/E5.mp3'), // E5
  77: require('../../assets/audio/F5.mp3'), // F5
  78: require('../../assets/audio/Gb5.mp3'), // Gb5
  79: require('../../assets/audio/G5.mp3'), // G5
  80: require('../../assets/audio/Ab5.mp3'), // Ab5
  81: require('../../assets/audio/A5.mp3'), // A5
  82: require('../../assets/audio/Bb5.mp3'), // Bb5
  83: require('../../assets/audio/B5.mp3'), // B5
  84: require('../../assets/audio/C6.mp3'), // C6
  85: require('../../assets/audio/Db6.mp3'), // Db6
  86: require('../../assets/audio/D6.mp3'), // D6
  87: require('../../assets/audio/Eb6.mp3'), // Eb6
  88: require('../../assets/audio/E6.mp3'), // E6
  89: require('../../assets/audio/F6.mp3'), // F6
  90: require('../../assets/audio/Gb6.mp3'), // Gb6
  91: require('../../assets/audio/G6.mp3'), // G6
  92: require('../../assets/audio/Ab6.mp3'), // Ab6
  93: require('../../assets/audio/A6.mp3'), // A6
  94: require('../../assets/audio/Bb6.mp3'), // Bb6
  95: require('../../assets/audio/B6.mp3'), // B6
  96: require('../../assets/audio/C7.mp3'), // C7
  97: require('../../assets/audio/Db7.mp3'), // Db7
  98: require('../../assets/audio/D7.mp3'), // D7
  99: require('../../assets/audio/Eb7.mp3'), // Eb7
  100: require('../../assets/audio/E7.mp3'), // E7
  101: require('../../assets/audio/F7.mp3'), // F7
  102: require('../../assets/audio/Gb7.mp3'), // Gb7
  103: require('../../assets/audio/G7.mp3'), // G7
  104: require('../../assets/audio/Ab7.mp3'), // Ab7
  105: require('../../assets/audio/A7.mp3'), // A7
  106: require('../../assets/audio/Bb7.mp3'), // Bb7
  107: require('../../assets/audio/B7.mp3'), // B7
  108: require('../../assets/audio/C8.mp3'), // C8
};
