/** Shared DOM-mode styles for MidiPlayerDOM and the progress screen. */
export const domStyles = {
  body: {
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    backgroundColor: '#111318',
    minHeight: '100%',
    display: 'flex',
    justifyContent: 'center',
    padding: '12px',
    color: '#E2E2E6',
    boxSizing: 'border-box' as const,
    overflowX: 'hidden' as const,
  },
  wrapper: {
    width: '100%',
    maxWidth: '520px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '16px',
  },
  tabRow: {
    flexDirection: 'row' as const,
    display: 'flex',
    gap: '12px',
    borderBottom: '1px solid rgba(255, 255, 255, 0.05)',
    paddingBottom: '8px',
  },
  tabBtn: {
    flex: 1,
    padding: '10px',
    borderRadius: '12px',
    backgroundColor: 'transparent',
    border: 'none',
    color: '#8A92A6',
    fontWeight: '700' as const,
    cursor: 'pointer',
    fontSize: '13px',
  },
  activeTabBtn: {
    flex: 1,
    padding: '10px',
    borderRadius: '12px',
    backgroundColor: 'rgba(168, 199, 250, 0.08)',
    border: '1px solid rgba(168, 199, 250, 0.2)',
    color: '#A8C7FA',
    fontWeight: '800' as const,
    cursor: 'pointer',
    fontSize: '13px',
  },
  
  // ─── Shared Button Styles ─────────────────────────────────────────────────
  
  gridBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '12px 0',
    borderRadius: '16px',
    backgroundColor: '#25282F',
    border: '1px solid rgba(255,255,255,0.04)',
    color: '#E2E2E6',
    fontSize: '14px',
    fontWeight: '800' as const,
    cursor: 'pointer',
    textAlign: 'center' as const,
    transition: 'all 0.2s',
  },
  gridBtnPlay: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '12px 0',
    borderRadius: '16px',
    backgroundColor: '#A8C7FA',
    border: 'none',
    color: '#0A305F',
    fontSize: '14px',
    fontWeight: '900' as const,
    cursor: 'pointer',
    textAlign: 'center' as const,
    transition: 'all 0.2s',
  },
  gridBtnDisabled: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '12px 0',
    borderRadius: '16px',
    backgroundColor: '#25282F',
    border: 'none',
    color: '#53565F',
    fontSize: '14px',
    fontWeight: '800' as const,
    cursor: 'not-allowed',
    textAlign: 'center' as const,
    opacity: 0.4,
    transition: 'all 0.2s',
  },
  answerBtn: {
    width: '54px',
    height: '54px',
    borderRadius: '27px',
    backgroundColor: '#A8C7FA',
    border: 'none',
    color: '#0A305F',
    fontSize: '15px',
    fontWeight: '900' as const,
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    transition: 'all 0.2s',
  },

  // Bottom action bar buttons (Start, Restart, Next)
  actionBtn: {
    width: '100%',
    padding: '12px 0',
    borderRadius: '16px',
    fontSize: '12px',
    fontWeight: '800' as const,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  primaryActionBtn: {
    backgroundColor: '#A8C7FA',
    color: '#0A305F',
    border: 'none',
    boxShadow: '0 2px 6px rgba(168, 199, 250, 0.25)',
  },
  secondaryActionBtn: {
    backgroundColor: '#25282F',
    color: '#E2E2E6',
    border: '1px solid rgba(255, 255, 255, 0.05)',
    boxShadow: 'none',
  },
  disabledActionBtn: {
    backgroundColor: '#25282F',
    color: '#53565F',
    border: '1px solid rgba(255, 255, 255, 0.05)',
    opacity: 0.4,
    cursor: 'not-allowed',
    boxShadow: 'none',
  },

  // ─── Layout Elements ──────────────────────────────────────────────────────
  
  card: {
    backgroundColor: '#1D2024',
    border: '1px solid rgba(255, 255, 255, 0.04)',
    borderRadius: '24px',
    padding: '18px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
  },
  answerContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
  },
  answerRow: {
    display: 'flex',
    flexDirection: 'row' as const,
    gap: '12px',
    alignItems: 'center',
    overflowX: 'auto' as const,
  },
  restartBtn: {
    display: 'flex',
    alignItems: 'center',
    padding: '12px 18px',
    borderRadius: '24px',
    backgroundColor: '#25282F',
    border: '1px solid rgba(255, 255, 255, 0.05)',
    color: '#E2E2E6',
    fontSize: '12px',
    fontWeight: '800' as const,
    cursor: 'pointer',
    marginLeft: 'auto',
  },
  metaLabel: {
    fontSize: '11px',
    color: '#8A92A6',
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: '1px',
    margin: '0 0 4px 0',
  },
  sectionTitle: {
    fontSize: '15px',
    fontWeight: '800' as const,
    color: '#E2E2E6',
    margin: '4px 0',
  },
  notesDivider: {
    height: '1px',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    margin: '8px 0',
  },
  openSourceBadge: {
    flexDirection: 'row' as const,
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    backgroundColor: 'rgba(168, 199, 250, 0.03)',
    border: '1px dashed rgba(168, 199, 250, 0.15)',
    borderRadius: '16px',
    padding: '14px',
    marginTop: '12px',
  },
  openSourceText: {
    flex: 1,
    fontSize: '11px',
    color: '#8A92A6',
    lineHeight: '16px',
    margin: 0,
  },
} as const;
