/** Shared DOM-mode styles for MidiPlayerDOM and the progress screen. */

// Base universal button styling for high-fidelity interactive elements (squircles)
const baseButton = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  height: '48px',
  minWidth: '56px',
  padding: '0 16px',
  borderRadius: '16px',
  fontSize: '13px',
  fontWeight: '800' as const,
  cursor: 'pointer',
  textAlign: 'center' as const,
  transition: 'all 0.2s',
  boxSizing: 'border-box' as const,
  border: '1px solid transparent',
};

export const domStyles = {
  body: {
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    backgroundColor: '#111318',
    minHeight: '100%',
    display: 'flex',
    justifyContent: 'center',
    padding: '12px',
    color: '#E2E2E6',
    boxSizing: 'border-box' as const,
    overflowX: 'hidden' as const,
  },
  wrapper: {
    width: '100%',
    maxWidth: '520px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '16px',
  },
  tabRow: {
    flexDirection: 'row' as const,
    display: 'flex',
    gap: '12px',
    borderBottom: '1px solid rgba(255, 255, 255, 0.05)',
    paddingBottom: '8px',
  },
  tabBtn: {
    flex: 1,
    padding: '10px',
    borderRadius: '12px',
    backgroundColor: 'transparent',
    border: 'none',
    color: '#8A92A6',
    fontWeight: '700' as const,
    cursor: 'pointer',
    fontSize: '13px',
  },
  activeTabBtn: {
    flex: 1,
    padding: '10px',
    borderRadius: '12px',
    backgroundColor: 'rgba(168, 199, 250, 0.08)',
    border: '1px solid rgba(168, 199, 250, 0.2)',
    color: '#A8C7FA',
    fontWeight: '800' as const,
    cursor: 'pointer',
    fontSize: '13px',
  },
  
  // ─── Shared Universal Button Styles (Squircles) ───────────────────────────
  
  primaryBtn: {
    ...baseButton,
    backgroundColor: '#A8C7FA',
    color: '#0A305F',
    fontWeight: '900' as const,
    boxShadow: '0 2px 6px rgba(168, 199, 250, 0.25)',
  },
  
  secondaryBtn: {
    ...baseButton,
    backgroundColor: '#25282F',
    borderColor: 'rgba(255, 255, 255, 0.05)',
    color: '#E2E2E6',
  },
  
  disabledBtn: {
    ...baseButton,
    backgroundColor: '#25282F',
    color: '#53565F',
    cursor: 'not-allowed',
    opacity: 0.4,
  },

  dashedBtn: {
    ...baseButton,
    backgroundColor: 'rgba(168, 199, 250, 0.08)',
    border: '1px dashed rgba(168, 199, 250, 0.3)',
    color: '#A8C7FA',
  },

  // ─── Layout Elements ──────────────────────────────────────────────────────
  
  card: {
    backgroundColor: '#1D2024',
    border: '1px solid rgba(255, 255, 255, 0.04)',
    borderRadius: '24px',
    padding: '18px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
  },
  answerContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
  },
  answerRow: {
    display: 'flex',
    flexDirection: 'row' as const,
    gap: '12px',
    alignItems: 'center',
    overflowX: 'auto' as const,
  },
  restartBtn: {
    display: 'flex',
    alignItems: 'center',
    padding: '12px 18px',
    borderRadius: '24px',
    backgroundColor: '#25282F',
    border: '1px solid rgba(255, 255, 255, 0.05)',
    color: '#E2E2E6',
    fontSize: '12px',
    fontWeight: '800' as const,
    cursor: 'pointer',
    marginLeft: 'auto',
  },
  metaLabel: {
    fontSize: '11px',
    color: '#8A92A6',
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: '1px',
    margin: '0 0 4px 0',
  },
  sectionTitle: {
    fontSize: '15px',
    fontWeight: '800' as const,
    color: '#E2E2E6',
    margin: '4px 0',
  },
  notesDivider: {
    height: '1px',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    margin: '8px 0',
  },
  openSourceBadge: {
    flexDirection: 'row' as const,
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    backgroundColor: 'rgba(168, 199, 250, 0.03)',
    border: '1px dashed rgba(168, 199, 250, 0.15)',
    borderRadius: '16px',
    padding: '14px',
    marginTop: '12px',
  },
  openSourceText: {
    flex: 1,
    fontSize: '11px',
    color: '#8A92A6',
    lineHeight: '16px',
    margin: 0,
  },

  // Notes card & textarea inside Theory Tab
  theoryNotesCard: {
    backgroundColor: '#111318',
    border: '1px solid rgba(255, 255, 255, 0.04)',
    borderRadius: '16px',
    padding: '16px',
    width: '100%',
    boxSizing: 'border-box' as const,
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '10px',
  },
  theoryNotesTextarea: {
    width: '100%',
    height: '90px',
    backgroundColor: '#111318',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: '12px',
    padding: '10px',
    color: '#E2E2E6',
    fontSize: '12px',
    outline: 'none',
    resize: 'none' as const,
    boxSizing: 'border-box' as const,
  },
} as const;
