/** Shared DOM-mode styles for MidiPlayerDOM and the progress screen. */

// Base universal button styling for high-fidelity interactive elements (squircles)
const baseButton = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  height: '48px',
  minWidth: '56px',
  padding: '0 16px',
  borderRadius: '16px',
  fontSize: '13px',
  fontWeight: '800' as const,
  cursor: 'pointer',
  textAlign: 'center' as const,
  transition: 'all 0.2s',
  boxSizing: 'border-box' as const,
  borderWidth: '1px',
  borderStyle: 'solid',
  borderColor: 'transparent',
};

export const domStyles = {
  body: {
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    backgroundColor: '#111318',
    width: '100%',
    height: '100vh',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    padding: '8px 12px',
    color: '#E2E2E6',
    boxSizing: 'border-box' as const,
    overflow: 'hidden' as const,
  },
  wrapper: {
    width: '100%',
    maxWidth: '520px',
    height: '100%',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
    boxSizing: 'border-box' as const,
  },
  wrapperLandscape: {
    width: '100%',
    maxWidth: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
    boxSizing: 'border-box' as const,
  },
  landscapeLayoutGrid: {
    display: 'flex',
    flexDirection: 'row' as const,
    gap: '16px',
    alignItems: 'stretch',
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  leftColumn: {
    flex: 1.1,
    minWidth: '0',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
    boxSizing: 'border-box' as const,
  },
  rightColumn: {
    flex: 0.9,
    minWidth: '0',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
    boxSizing: 'border-box' as const,
  },
  tabRow: {
    flexDirection: 'row' as const,
    display: 'flex',
    gap: '12px',
    borderBottom: '1px solid rgba(255, 255, 255, 0.05)',
    paddingBottom: '8px',
  },
  tabBtn: {
    flex: 1,
    padding: '10px',
    borderRadius: '12px',
    backgroundColor: 'transparent',
    borderWidth: 0,
    color: '#8A92A6',
    fontWeight: '700' as const,
    cursor: 'pointer',
    fontSize: '13px',
  },
  activeTabBtn: {
    flex: 1,
    padding: '10px',
    borderRadius: '12px',
    backgroundColor: 'rgba(168, 199, 250, 0.08)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(168, 199, 250, 0.2)',
    color: '#A8C7FA',
    fontWeight: '800' as const,
    cursor: 'pointer',
    fontSize: '13px',
  },
  
  // ─── Shared Universal Button Styles (Squircles) ───────────────────────────
  
  primaryBtn: {
    ...baseButton,
    backgroundColor: '#A8C7FA',
    color: '#0A305F',
    fontWeight: '900' as const,
    boxShadow: '0 2px 6px rgba(168, 199, 250, 0.25)',
  },
  
  secondaryBtn: {
    ...baseButton,
    backgroundColor: '#25282F',
    borderColor: 'rgba(255, 255, 255, 0.05)',
    color: '#E2E2E6',
  },
  
  disabledBtn: {
    ...baseButton,
    backgroundColor: '#25282F',
    color: '#8E919A',
    cursor: 'not-allowed',
    opacity: 0.55,
  },

  correctBtn: {
    ...baseButton,
    backgroundColor: 'rgba(129, 199, 132, 0.12)',
    borderColor: 'rgba(129, 199, 132, 0.3)',
    color: '#81C784',
    fontWeight: '900' as const,
  },

  wrongBtn: {
    ...baseButton,
    backgroundColor: 'rgba(229, 115, 115, 0.12)',
    borderColor: 'rgba(229, 115, 115, 0.3)',
    color: '#E57373',
    fontWeight: '900' as const,
  },

  dashedBtn: {
    ...baseButton,
    backgroundColor: 'rgba(168, 199, 250, 0.08)',
    borderStyle: 'dashed',
    borderColor: 'rgba(168, 199, 250, 0.3)',
    color: '#A8C7FA',
  },

  // ─── Layout Elements ──────────────────────────────────────────────────────
  
  card: {
    backgroundColor: '#1D2024',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: '24px',
    padding: '18px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
  },
  answerContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
  },
  answerRow: {
    display: 'flex',
    flexDirection: 'row' as const,
    gap: '12px',
    alignItems: 'center',
    overflowX: 'auto' as const,
  },
  restartBtn: {
    display: 'flex',
    alignItems: 'center',
    padding: '12px 18px',
    borderRadius: '24px',
    backgroundColor: '#25282F',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(255, 255, 255, 0.05)',
    color: '#E2E2E6',
    fontSize: '12px',
    fontWeight: '800' as const,
    cursor: 'pointer',
    marginLeft: 'auto',
  },
  metaLabel: {
    fontSize: '11px',
    color: '#8A92A6',
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: '1px',
    margin: '0 0 4px 0',
  },
  sectionTitle: {
    fontSize: '15px',
    fontWeight: '800' as const,
    color: '#E2E2E6',
    margin: '4px 0',
  },
  notesDivider: {
    height: '1px',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    margin: '8px 0',
  },
  openSourceBadge: {
    flexDirection: 'row' as const,
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    backgroundColor: 'rgba(168, 199, 250, 0.03)',
    borderWidth: '1px',
    borderStyle: 'dashed',
    borderColor: 'rgba(168, 199, 250, 0.15)',
    borderRadius: '16px',
    padding: '14px',
    marginTop: '12px',
  },
  openSourceText: {
    flex: 1,
    fontSize: '11px',
    color: '#8A92A6',
    lineHeight: '16px',
    margin: 0,
  },

  settingRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.01)',
    padding: '12px 14px',
    borderRadius: '16px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(255,255,255,0.04)',
  },
  toggleContainer: {
    width: '44px',
    height: '24px',
    borderRadius: '12px',
    position: 'relative' as const,
    cursor: 'pointer',
    transition: 'background-color 0.2s ease, border-color 0.2s ease',
    boxSizing: 'border-box' as const,
  },
  settingTitle: {
    fontSize: '11px',
    fontWeight: '800' as const,
    color: '#A8C7FA',
    margin: '0 0 6px 0',
    textTransform: 'uppercase' as const,
    letterSpacing: '1px',
  },
  toggleLabel: {
    fontSize: '13px',
    fontWeight: '800' as const,
    color: '#E2E2E6',
    margin: 0,
  },
  toggleSublabel: {
    fontSize: '11px',
    color: '#8A92A6',
    margin: '2px 0 0 0',
  },
  modalOverlay: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(10, 11, 14, 0.85)',
    backdropFilter: 'blur(8px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100000,
    padding: '24px',
  },
  modalCard: {
    backgroundColor: '#1E2025',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: '24px',
    padding: '28px',
    maxWidth: '380px',
    width: '100%',
    boxShadow: '0 12px 40px rgba(0, 0, 0, 0.5)',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '20px',
    alignItems: 'center',
    textAlign: 'center' as const,
  },
  modalIconContainer: {
    width: '56px',
    height: '56px',
    borderRadius: '28px',
    backgroundColor: 'rgba(233, 161, 23, 0.1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#E9A117',
  },
  modalCheckboxRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    cursor: 'pointer',
    userSelect: 'none' as const,
    padding: '6px 12px',
    borderRadius: '12px',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  progressCard: {
    backgroundColor: 'rgba(168, 199, 250, 0.02)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: '24px',
    padding: '12px 18px',
    display: 'flex',
    flexDirection: 'row' as const,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  practiceControlBtn: {
    flex: 1,
    width: '100%',
    height: '44px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 'auto',
    margin: 0,
  },
  practiceControlBtnWrapper: {
    flex: 1,
    display: 'flex',
  },
  practiceControlRowLandscape: {
    display: 'flex',
    gap: '8px',
    width: '100%',
    marginBottom: '4px',
  },
  practiceControlRowPortrait: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
    width: '100%',
    marginBottom: '4px',
  },
  practiceControlSubRow: {
    display: 'flex',
    gap: '8px',
    width: '100%',
  },

  // Notes card & textarea inside Theory Tab
  theoryNotesCard: {
    backgroundColor: '#111318',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: '16px',
    padding: '16px',
    width: '100%',
    boxSizing: 'border-box' as const,
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '10px',
  },
  theoryNotesTextarea: {
    width: '100%',
    height: '90px',
    backgroundColor: '#111318',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(255,255,255,0.06)',
    borderRadius: '12px',
    padding: '10px',
    color: '#E2E2E6',
    fontSize: '12px',
    outline: 'none',
    resize: 'none' as const,
    boxSizing: 'border-box' as const,
  },
} as const;
